// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mptuqwislbgidpcwerlq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1wdHVxd2lzbGJnaWRwY3dlcmxxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3NjI3ODMsImV4cCI6MjA2ODMzODc4M30.xhJDSckmZ_tMQx6IK8r1A4Ls9HVDNVVTXo8CElyk53o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});